---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tt-rss-config
  namespace: media
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
