---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
      chart: jellyfin
      version: 8.2.0
  interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/jellyfin
      tag: v10.7.7
    env:
      TZ: "America/Detroit"
      JELLYFIN_CACHE_DIR: /config/cache
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "download-box"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - "jellyfin.${SECRET_DOMAIN}"
            secretName: jellyfin-cert
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1001
      fsGroup: 1001
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "gypsy"
            path: /pool/storage-0/media
        mountPath: /media
    resources:
      requests:
        memory: 500Mi
        cpu: 500m