apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: home-assistant-secrets
    namespace: home
stringData:
    SECRET_TRUSTED_PROXIES_1: ENC[AES256_GCM,data:7daLmL0CWpTf2KNH,iv:V+Qa2U3U8LY6uE+20STHlYmAeREqmn+/7WgJ+XQRQBs=,tag:6cO2hN+rNbKx/tfrwERKvQ==,type:str]
    SECRET_TRUSTED_PROXIES_2: ENC[AES256_GCM,data:riN0ciniB48P6pT4,iv:xfcfxI9tlObHHAbIBJ37YUK907ZYSfBdzL60ipNwNgE=,tag:5CA1EdX8m5RF5DmBgeJy0w==,type:str]
    SECRET_TRUSTED_PROXIES_3: ENC[AES256_GCM,data:fJeaQGP8LHF9UCbaeWq3,iv:+8JDdJG2iSNqv+ZTMzsQgE/AfJwGE4wS587HcEI7DGk=,tag:PaVPYqsEE1snEWdy1hk2Rw==,type:str]
    SECRET_ZONE_HOME_HOUSE_NUMBER: ENC[AES256_GCM,data:J2bREg==,iv:vIlw72wTOi+shf47OhffhpU9M+yvFWRJvNa1Go3WFjc=,tag:sFIAN/GTG1xf56EvnH2s2g==,type:int]
    SECRET_ZONE_HOME_POSTAL_CODE: ENC[AES256_GCM,data:oZqhj1k=,iv:mIcAHLHuHnNtcWWYLW7PG39Trm1NCjpWqolC/b+Blso=,tag:RJwRc+DPjLp+gGi13T/hXA==,type:int]
    SECRET_ZONE_HOME_LATITUDE: ENC[AES256_GCM,data:t66kYJQpEWMs,iv:jDHdSf2l1TZF/Xh8g3fmQ9mxN3UNs0A6bHClLHQy73w=,tag:rKSbMDryCZsA3N2VpS5jrg==,type:float]
    SECRET_ZONE_HOME_LONGITUDE: ENC[AES256_GCM,data:dO3oOHnXtvnSvg==,iv:AtM7biQXRKQfVMddOqXNnSiHBtYNx7VXR1lH0tF6ugU=,tag:S+rqh5WUE3oGdXfcURCf5Q==,type:float]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-31T00:35:57Z"
    mac: ENC[AES256_GCM,data:oL+KTEQ3EcJJSpq/Mmw3hiuPzh/UAmql+NdWMWI+55lEp9ElHywCRXJjmJGJhsle9Oadb1tvFOhbQItFKTykuEqVSL7cR+mDvoPbEEm6w6SLl8k5+7MgJ7d50GHMwx7TID41CyfjvKLFXmbDU4ei/esMt6ngG+XMQvJklifIVG4=,iv:FQrK22157T3WmeQ2An43WfOw4anpIEQ+oX+xkO6twuY=,tag:u/uceDOVH28B+c6i+fmlCQ==,type:str]
    pgp:
        - created_at: "2021-10-31T00:26:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4ul+lujJ3/pAQ/9Ge+7cx4g5umWZ+ejsXmW5v94cQVGQwtc6EY7/qNdhCJ8
            Ev6wba18Hut1tq1ngqhq72flRjVHk6jQhDkdsKge04ZN9kVnOldqDJFFeiPv4Iep
            34o6bRvq0eW9c6YrrbbU3RgBVYKYBUoU5hvGr7fxmMl/E+hWk4EkRjxik9RFOzfr
            md3g84XitFm3VYenZ8Zm4zwF1pOdHHvh89MPfoAEhBda6/+0fX7nxgHk7at9Qxpv
            T/9aGbe692end0Z4+zDmHlUJUBVdNdQig9S525KDOusypo6SmSP75JDfsso14fP4
            ISKT3pdcEIFjgzp/tTCQSLvPKbYxaNuNZaiUt+CpESVMggs3XdF6NTj2LBr29ptN
            Z6Lcygrq47XO41G8slZEdU8L2e844WguJOWxCCwgd6mYflQRtHUX2cv9i5GAHIj1
            R/5cSCoxKrP7Ydvgncc5f2QM4+Wh0+VwY9iT8MIgORrX7OVmr9gjF5Eqo8TcqY9d
            BnLA2c5Xt63Hj3fO9lKO6N75R03VMqGSm/eVnJo73C9o5pcQcQjAGsEkEq7efD/C
            rG5MEVom71FwMnSCH4wEgGr9Zf0eWw5cD/6Ut7g6N2BJg2pfasfyMuZSp1EvaAIU
            vsgsgIAJbwN+CDMCp3nhZX/wDTwKAShNO4AInFxvRHX03EK7PPFAKJXrS5OVlhXU
            aAEJAhVCmjQMn2cXFliBuZ6CSLZXoCZm0RqgeqwH8ETHPCl/yIci0TRbtZ/Zge53
            qNCzIhSIj4e+Q5RxgOhiMZ9vT6mMGYnVtUx9eSCQaJpGbLnDf1iNdamUaan8raB2
            c9J3sYBSOwGp
            =oxNH
            -----END PGP MESSAGE-----
          fp: DA82D9B6FC38DD11F078AF19C206F2FB9DCCC629
        - created_at: "2021-10-31T00:26:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8q/csSOs+7rAQ//cayzmw4e1MIVQtBRlRLUjhednAXjS1nrJlo66NBsspX+
            PZSTc3jdztQTN7seigPM/k+scMEUuo5uOWUeuNIHX3RvsRKUBiXQYhJwzBRf532X
            Q49MUArcbsfDFLbqUd2qoleSynCm/e7bJCKBV0yeTFNDYTZ0Ya//UVDZ3ywgvzH4
            Fs8N3p60VskItuwathbJLdl9u68YQf4pj0PzWvZXSdookmwmm/V8jQNUoI8VzM2V
            v0v82fwZFQhJvZP5UgCsr18IGjVV/baYpKoKAUyVj04EZMmCE4Ro67Fv9poEbLFp
            xwp1g1RC5C4l7u23Q7i/+wduMkWnhoKwdCyZz8zsqbkFYUHIYhwtvm1uYX3OcLoT
            371WGd7tWgMhJySAktEZGvmQ+8YdUcwAUKeHfnmKmxyqE5luBoMwVFVZhmyexuoV
            LoN8hEhDov+x8PnmWVNxrN4NR7w3SXT1t5L32GHQf57x9PnjR5VoN1SH8NYEr3Wd
            BCE0i9m1/ykUNMKGaWpjCngdsg0HsXSK5tMnUbdCp3jewzi/QhkYrIBIfAgSZLSJ
            iyn1RFVY25JGFOYn1Ja2KGqNNVhWlcccNyT4U/0qpMzejx20tgepNPKcC2RnQqU0
            DRBisHdh6dUm8BGisQFzrAW4lOkcS7j+V4a9NHwtmeRabVjUWcaL/i+J5e1xBLzU
            aAEJAhVzEE+FiKB5i6uWB7jNknTENZBOs6+LnIog3HaF9M78+IMFk/Y2uZ4wCT12
            g94L6+k9sQ4qSVhaNgs7mV9O+k7KrERY/RxKmldeETauomM7s+WQKyhvdbQ7D3mY
            l4FYRzsAl2+k
            =p55F
            -----END PGP MESSAGE-----
          fp: 68A86A952C39741BA73F23318E6EE8B38327DF74
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
