apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: home-assistant-secrets
    namespace: home
stringData:
    HASS_TRUSTED_PROXIES_1: ENC[AES256_GCM,data:3qNKeFCeyEX8U6G0,iv:MdaB4tbqHHYR48P8Vdud3qmPintnxHGCyaI7yEkScXg=,tag:DEVVJ1RBa8r37KrEMdASrw==,type:str]
    HASS_TRUSTED_PROXIES_2: ENC[AES256_GCM,data:wXiUKUKfom9B618l,iv:tXIExQTFKau2doIbgHf8zD3Mp6FEnNS0vYeMEPMaMPQ=,tag:dw5H3E4wSI3hljZDfMlMbA==,type:str]
    HASS_TRUSTED_PROXIES_3: ENC[AES256_GCM,data:jZIaJ+tR259edPsS,iv:Q09bL+HtEp7CJz1e/V9Lk8sbnJSoMTCr5x2CKKJFt4k=,tag:WfDw8CsIUADvoT0I96ub7Q==,type:str]
    HASS_HOME_HOUSE_NUMBER: ENC[AES256_GCM,data:VTKxtA==,iv:6A60s36shnT4Dj9TncHJExuWU8+fQ2rGN3pBX15y2GY=,tag:b0WBa0AZ8S6qj5/hwUOlSg==,type:str]
    HASS_HOME_POSTAL_CODE: ENC[AES256_GCM,data:7Ztod/8=,iv:q+ulM/jYEme6YjfOTNh+wdulT9zkX0/qoJ/w2V9M78s=,tag:GfFHrjjLy5Gxp1cct5u5gg==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:fIMDL88GTPcY,iv:ltB1O/rV2CUP5e6FxmBJq5/o0dr3yoBeSIxzGIVWf2o=,tag:LNTwHaDmlFSgRf8wkCjWEw==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:BR5qhBFV48C2aA==,iv:/GOsuK8URnPm7Ob6pgfW1puYZCGAjBV7DYQna/L6tvo=,tag:lApq9lhaTmTSx8teGmNEcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-04T23:41:28Z"
    mac: ENC[AES256_GCM,data:HPL8/B9zm4bW49m3T5zc/T6DxXA58WcmRHkB/+9RDjscWY8Ln3Zjj6gF+D0iUARrNLs0UKZQKMm8C8moLPf+EB9/h/Vj2fXRaaARQvaJjBUdfK16JwTua6sfi3lr5mlr8eHYVG9gsheDE4ImI2IMo0rnBMtXoS3GMt2kZ6hslEI=,iv:iu1QX7uP4eXESYF7AUPrhekqlBF/chdn4NP7KowQoPQ=,tag:3xKlj48InqKKR9VMHqYKqw==,type:str]
    pgp:
        - created_at: "2021-10-31T00:26:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4ul+lujJ3/pAQ/9Ge+7cx4g5umWZ+ejsXmW5v94cQVGQwtc6EY7/qNdhCJ8
            Ev6wba18Hut1tq1ngqhq72flRjVHk6jQhDkdsKge04ZN9kVnOldqDJFFeiPv4Iep
            34o6bRvq0eW9c6YrrbbU3RgBVYKYBUoU5hvGr7fxmMl/E+hWk4EkRjxik9RFOzfr
            md3g84XitFm3VYenZ8Zm4zwF1pOdHHvh89MPfoAEhBda6/+0fX7nxgHk7at9Qxpv
            T/9aGbe692end0Z4+zDmHlUJUBVdNdQig9S525KDOusypo6SmSP75JDfsso14fP4
            ISKT3pdcEIFjgzp/tTCQSLvPKbYxaNuNZaiUt+CpESVMggs3XdF6NTj2LBr29ptN
            Z6Lcygrq47XO41G8slZEdU8L2e844WguJOWxCCwgd6mYflQRtHUX2cv9i5GAHIj1
            R/5cSCoxKrP7Ydvgncc5f2QM4+Wh0+VwY9iT8MIgORrX7OVmr9gjF5Eqo8TcqY9d
            BnLA2c5Xt63Hj3fO9lKO6N75R03VMqGSm/eVnJo73C9o5pcQcQjAGsEkEq7efD/C
            rG5MEVom71FwMnSCH4wEgGr9Zf0eWw5cD/6Ut7g6N2BJg2pfasfyMuZSp1EvaAIU
            vsgsgIAJbwN+CDMCp3nhZX/wDTwKAShNO4AInFxvRHX03EK7PPFAKJXrS5OVlhXU
            aAEJAhVCmjQMn2cXFliBuZ6CSLZXoCZm0RqgeqwH8ETHPCl/yIci0TRbtZ/Zge53
            qNCzIhSIj4e+Q5RxgOhiMZ9vT6mMGYnVtUx9eSCQaJpGbLnDf1iNdamUaan8raB2
            c9J3sYBSOwGp
            =oxNH
            -----END PGP MESSAGE-----
          fp: DA82D9B6FC38DD11F078AF19C206F2FB9DCCC629
        - created_at: "2021-10-31T00:26:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8q/csSOs+7rAQ//cayzmw4e1MIVQtBRlRLUjhednAXjS1nrJlo66NBsspX+
            PZSTc3jdztQTN7seigPM/k+scMEUuo5uOWUeuNIHX3RvsRKUBiXQYhJwzBRf532X
            Q49MUArcbsfDFLbqUd2qoleSynCm/e7bJCKBV0yeTFNDYTZ0Ya//UVDZ3ywgvzH4
            Fs8N3p60VskItuwathbJLdl9u68YQf4pj0PzWvZXSdookmwmm/V8jQNUoI8VzM2V
            v0v82fwZFQhJvZP5UgCsr18IGjVV/baYpKoKAUyVj04EZMmCE4Ro67Fv9poEbLFp
            xwp1g1RC5C4l7u23Q7i/+wduMkWnhoKwdCyZz8zsqbkFYUHIYhwtvm1uYX3OcLoT
            371WGd7tWgMhJySAktEZGvmQ+8YdUcwAUKeHfnmKmxyqE5luBoMwVFVZhmyexuoV
            LoN8hEhDov+x8PnmWVNxrN4NR7w3SXT1t5L32GHQf57x9PnjR5VoN1SH8NYEr3Wd
            BCE0i9m1/ykUNMKGaWpjCngdsg0HsXSK5tMnUbdCp3jewzi/QhkYrIBIfAgSZLSJ
            iyn1RFVY25JGFOYn1Ja2KGqNNVhWlcccNyT4U/0qpMzejx20tgepNPKcC2RnQqU0
            DRBisHdh6dUm8BGisQFzrAW4lOkcS7j+V4a9NHwtmeRabVjUWcaL/i+J5e1xBLzU
            aAEJAhVzEE+FiKB5i6uWB7jNknTENZBOs6+LnIog3HaF9M78+IMFk/Y2uZ4wCT12
            g94L6+k9sQ4qSVhaNgs7mV9O+k7KrERY/RxKmldeETauomM7s+WQKyhvdbQ7D3mY
            l4FYRzsAl2+k
            =p55F
            -----END PGP MESSAGE-----
          fp: 68A86A952C39741BA73F23318E6EE8B38327DF74
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
