---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.10.3
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    configInline:
      peers:
        - peer-address: 10.4.20.1
          peer-asn: 64512
          my-asn: 64512
      address-pools:
        - name: default
          protocol: bgp
          addresses:
            - "${METALLB_LB_RANGE}"
          avoid-buggy-ips: true
    prometheus:
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    speaker:
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
