---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-download-media
provisioner: nfs
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-download-media
spec:
  storageClassName: nfs-download-media
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "gypsy.lan"
    path: /pool/storage-0/media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-download-media
  namespace: media
spec:
  storageClassName: nfs-download-media
  resources:
    requests:
      storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
