---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: kube-system
spec:
  interval: 15m
  dependsOn:
    name: node-feature-discovery
    namespace: kube-system
  chart:
    spec:
      chart: intel-gpu-plugin
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    controller:
      type: daemonset
      strategy: RollingUpdate
    image:
      repository: docker.io/intel/intel-gpu-plugin
      tag: 0.24.0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"