kind: Secret
ansible_user: ENC[AES256_GCM,data:hS9L,iv:weOY5mtJ99E6hUXiAVJT8B8IKc6IAY3FNlz59PWi3DQ=,tag:/MYvpLcoC7QmZXRWkK65Uw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:YwhJmbUqkONdlLRK/YIQbixpiPE=,iv:eZh4qZf8+Cv9TVmlRZMEDkqlxnVD8F9yFDLnLP0lZlw=,tag:uYGaBLWOBuHbRTyYO9/yYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-05T00:28:47Z"
    mac: ENC[AES256_GCM,data:vAsKf0f7jZ6ozx7KcF2nbJmcgqTfmNlOSXHdGlM8GeJSRpXukaX16F2aSpOAqJzhbsO3vvJ/3SI2uB54hPLnHOugG7JWMNm7QebD2zGfC5grdM5ywRsA39QVsvbXqmI1L2+6prD0qGU06A9+9OM8cOL2JEfuhGw30bCmZly4gRk=,iv:/sykZECjqisSXhTJ3xYY4tYTIpNSA9VkI3i6tn3yILk=,tag:OgU0T0lWV5j9cpMWajOZzg==,type:str]
    pgp:
        - created_at: "2021-11-05T00:28:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8q/csSOs+7rAQ/9ESH6Ct7FhV2ZVFHgfE6XTosJ6Yh513FxkPwrRCesarkw
            /scdBx/hYAEKZ6xtfD/zzUAhAKQo8WwPafL+3PDft2sFBnsPqGHc5Wk1XQMpyXPB
            hkDVgq3IsLTMybB3xKxGXRwgJC/x6Mork93aQ7KoamXxEHb7Zp122+b+CMUnNr9a
            pGch0uqNWkotFX5wU0HNyjx60+XaLHELw+uewa4Z6YiICiOxtRc+ilq7YhgbAe9M
            NO0Fk9+tQWkBeZmeI9faDpt8lhmgSm8lc1lOZIYKT/SDBK7nM80n/BEJjq8jA3pA
            qwhyAxw9AuncYb/Can7wG/qY6WGrJYrKwaXUoOAyUWAzXnCVOdI5aHov3lBCbgCh
            QSY5dMrMbXmJx64W4FJO0KIF79IEeNWVShRCV6vSvZuddYbCC79dkBqXKrFviQ+R
            5AfMrAmrHJNB8Qd95LnMBaD6HP7CIf6Wdyf3d3Z+C0oAcf/511BrJ4DQfDgYeo70
            8o7rOelmN7zoUls/hzh4CBeRuhLtHeTnsmdtra+oOEBY0N6tz6Brq78sKSVfq5vq
            kZOSiiMOL4pKE0wFdZSICWXR++9f7n1GG9i46GPE1GePQwGoKW4t3DdJU6PK5z3A
            eZqy6ySFQMCeizVUgSzadShcXnjWsAE1rqus1k8qSHxO3sAdUmM9VIvFAUJXPATU
            aAEJAhVJ+vOZVd/5g5CI+uO2Xns8JyI6oPl6Uj76KixqmMRNqPCUGFC+Zfk+dlxD
            IELiKk4+Kw3/5tlzBlt/cjt5yxwM7+9JjJB2d+NZqGNQvdOVyN50EY8V5w/Cv1ou
            1wIsrsbuvKcM
            =lJE3
            -----END PGP MESSAGE-----
          fp: 68A86A952C39741BA73F23318E6EE8B38327DF74
    unencrypted_regex: ^(kind)$
    version: 3.7.1
