---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: home
spec:
  replicas: 3
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 4
      memory: 6Gi
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: default
      metallb.universe.tf/loadBalancerIPs: ${SVC_RABBITMQ_ADDR}
  persistence:
    storageClassName: local-path