---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: definition
  namespace: home
spec:
  replicas: 3
  service:
    type: LoadBalancer
  persistence:
    storageClassName: local-path