---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: home
spec:
  replicas: 3
  service:
    type: LoadBalancer
    loadBalancerIP: ${SVC_RABBITMQ_ADDR}
  persistence:
    storageClassName: local-path