---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb
      version: 4.10.6
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "influxdb"
      tag: "1.8.10-alpine"
    persistence:
      enabled: true
      existingClaim: influxdb-data
    securityContext:
      runAsUser: 1000
      runAsGroup: 1001
      fsGroup: 1001
    setDefaultUser:
      enabled: true
      user:
        password: ${SECRET_INFLUX_ADMIN_PASSWORD}
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hostname: "influx.${SECRET_DOMAIN}"
      secretName: influx-cert
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
