---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-storage
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce