---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: emqx
      version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: emqx-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    replicaCount: 3
    recreatePods: true
    emqxConfig:
    service:
      type: LoadBalancer
      externalIPs:
        - ${SVC_EMQX_ADDR}
      externalTrafficPolicy: Local
    ingress:
      dashboard:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "mqqt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - "mqqt.${SECRET_DOMAIN}"
            secretName: mqqt-cert
    metrics:
    persistence:
      
