---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tvheadend
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: tvheadend
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  image:
    repository: ghcr.io/linuxserver/tvheadend
    version: "version-eb59284b"
  env:
    TZ: "Americal/Detoit"
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "tvheadend.${SECRET_CLUSTER_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - "tvheadend.${SECRET_CLUSTER_DOMAIN}"

    resources:
      requests:
        memor: 2Gi
        cpu: 1
    
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/external-dvb-device
                operator: In
                values:
                  - true
