# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Ha75LqWyqX+6vvmSe9xqyoSmqhoh1lrnYypPElgJI7qX/9fPMg==,iv:FteA99auP0goWfO5RASmdRpA+fCTAtm2B5gXni9smWg=,tag:cNoBHJTZaAtGGGFzckuAoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-05T00:28:44Z"
    mac: ENC[AES256_GCM,data:7KfTZOtpMILmtHugPbu9LTFXY7fbO+91PQ9IMYI/1CvCVHpD3ES/DM9hX5NameZPCU4n0S/pZE58muy9SYEiLOn3kzEZ/mD5NFmybIuW2+GQ4egBk4aKcsc2QsH4FHyliXcS905YvQkqZlrmfyenNyGFyBu345AbIzbB0ahYSHI=,iv:ysU4LdNrazMgdeH/n4/1+Jn36r4f/nZrIB6Iys0dYCY=,tag:srnhnpUGm7unHD9TC5/zDg==,type:str]
    pgp:
        - created_at: "2021-11-05T00:28:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4ul+lujJ3/pAQ//fhoJA8TmRD58GJtLkJi3/9xK1+Q6t6GjnYyuJpG2NkeO
            B/Ms3FJegIF8+Sncrv6uZjVyR/s6VVL6PHPvfclSa8eI75Uy8QWOZUIjm6jBvGCD
            voir7JuiUeUcdAucA63OKf1GucpF6z8ifoH2sihaVTLcuNjdYECtPAXqOgmRUwie
            L7ta1VmUqKAUznvQPyNqn5EXw7tjUex2mfjEsP7Fn33Qp0DRxLaQj6pNsiwrdAtT
            6An89+GFiJo20XYX1e6EyVTNbq5/x9RMMdXEEZc99AGYEoT3WymI9qFBwcFjzDdc
            vFp/aL+0GrcuWDk3nEO52fMRGF9oBsrae+FIFpqrRa5b9oV7m5DcbMHPznrZLreT
            75BC5nlhOH2cgjqJsttFOBzHNpmXAYKW/td2RXXvi6JbQ7mbapNv92vG55+Gf3Vx
            sei5g4Kbo2rWQAj8YJYS3hEWixhXZQwSHh6k5bD9mIZcFtzh+65qtBKcl9kFKzyO
            9kt1l7CYN2pMhPu/xgWMyD7OFSh4w8a1LIl8LrD+1ygn1SzaeuFoEjTZC1Ep+WJM
            4NDrXkqCKRN8IoHcZWpLwrpiWyJ/y6s0oGJPy0SPaWRBC0TZJwXLzcvMW+4xXjBs
            ai31ZTGC9Y8CJZiWHJdoX4hoD3RRcfePPfkohN21Pd8I1pqZ/Hket4dzojGeuezU
            aAEJAhVpSVU95tPjaDvvW3zUMDhxQOripFpfATIsDW4hYPHejferNvsmlfZIp7o0
            R+ZTtlcq0VL/dkzX9wSyGR5BE9JSO8CZpj9Er2N1sfIJ3lJX/zjHFOuZkJ8/+A1t
            /moMGzqljpS4
            =k5yS
            -----END PGP MESSAGE-----
          fp: DA82D9B6FC38DD11F078AF19C206F2FB9DCCC629
        - created_at: "2021-11-05T00:28:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8q/csSOs+7rARAAkSSexRENpdL7+WNcFXwLeDCIKENLiZipdQtBKMq6BEg2
            nnqtjF0/1foV30h8bJ5uOUItnYvIkrxI9ID4S2ME87+aNMEfvlrb244p/HdDsVTx
            F0gGjf3sbg7F/WDzT13HfDjqSUOF3b1rw3HPyRjllUZbXzHTUStNQzlaprJ7WNnq
            hQabB5YarKgeIzXHygGGQZYvh7a7y9//F/9yuoaQ6ExAqD701oLHDKE3FZWkqnPy
            wH/juQe6i9idOzysdRsS2/HAvBzn/S2NHYy46enA3+c5bm493hPR2SRINloSq7sp
            hQCLWu/EEDBqLrH5Cwnovv3i0ubEpdUzaasmVSyq7APntW94EGFnkCKvQQg6SDMv
            MwMVwMNbLPydNAs2xG+1Woxdhdk9s4b/BGW1qaIpviAujJqvwNT7AFf13luBe2J+
            UvV8tDJsW4JDGwRx6ZX696RX3RZ65QIcNh6jGkiGI4z3E9KE8Q3ntuQMCY1i2zrB
            pA8zPwGcLX2Z2CdJFEs0x9Ly7xDQRtq9GCXWYz+wsAsh/8E13OszCr3etjCN8RM8
            JPi2T6Hh0b7TcovezZSgatKK4e8hh4HSpYd49TmCm2nbo0cRAqOTng5u682kOYej
            FgDmgBwMYHpa5WSje+mkuqxvqBDcD1B1pSIACu79YcTL7PB4JLr4cX0q/HZjlLzU
            aAEJAhUcVgtPrqerKyWcEODcob5bai27kCYlFehZPctpaC9jh5/s8RUu6C4eyH5S
            mt/WeAA1QXMMec7DLwJHmN2+9lb0FRNZpSi4mDPA3qrFAvajFpyv1SW5HTZSEWKw
            lj/+XUv2QfQy
            =WIIL
            -----END PGP MESSAGE-----
          fp: 68A86A952C39741BA73F23318E6EE8B38327DF74
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
